# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('tested.csv')

df

df.head()

df.shape

df.describe()

df['Survived'].value_counts()

sns.countplot(x=df['Survived'], hue = df['Pclass'])

df['Sex']

sns.countplot(x = df['Sex'] , hue = df['Survived'])

df.groupby('Sex')[['Survived']].mean()

df['Sex'].unique()

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
df['Sex'] = labelencoder.fit_transform(df['Sex'])
df.head()

df["Sex"],df["Survived"]

df["Survived"]

sns.countplot(x = df['Sex'], hue = df['Survived'])

df.isna().sum()

df = df.drop(['Age'],axis  = 1 )

df_final = df
df_final.head()

df_final.isnull().sum()

x = df[["Pclass", "Sex"]]
y = df["Survived"]

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

log.fit(x_train,y_train)

pred = print(log.predict(x_test))

print(y_test)

import warnings

warnings.filterwarnings("ignore")

res = log.predict([[2,1]])

if(res==0):
  print("so sorry ! Not Survived")
else:
  print("Survived")

